### ISSUE TITLE
crashes dedicated server b1502 while looking for client side classes

### ISSUE THREAD

**Issue by kreezxil** [FusionLord/CabinetsReloaded#1]
Issue: crashes dedicated server b1502 while looking for client side classes

crash report:
https://gist.github.com/8681415972f8e2bd7f1b

fml server latest:
https://gist.github.com/cf84b999cc0834d5efeb

**Comment by FusionLord** [comment]
Thank you, this will be fixed in the next version.

**Comment by kreezxil** [comment]
Ok, you fixed the crashing issue, but the crafting recipe doesn't appear in nei and you can't force the crafting recipe in a crafting table either. :(
