### ISSUE TITLE
odd crash on dedicated server startup, not sure if I can duplicate

### ISSUE THREAD

**Issue by kreezxil** [FusionLord/CabinetsReloaded#2]
Issue: odd crash on dedicated server startup, not sure if I can duplicate

crash report:
https://gist.github.com/81d2f98ceb9b1cc8e3c9

fml server latest:
https://gist.github.com/59d537e74da315d984c0

**Comment by kreezxil** [comment]
Ok, I'm definitely duplicating it now.

Issue: creash on dedicated server startup, this didn't happen until I creatively pulled one into the world and placed it

crash report:
https://gist.github.com/3872278154c2e7465134

fml server latest:
https://gist.github.com/9cebf0b97990e9c3a150

**Comment by FusionLord** [comment]
Yes I am aware of this issue and has been fixed in the version I will be releasing today... just polishing for the release.
